build:
	go build .
run:
	go run .
test:
	go test -v ./...

# prepend with '@' if you don't want to see the command but only the result
#build:
#	@go build .
#run:
#	@go run .
#test:
#	@go test -v ./...

