version: "3"

services:

  postgres:
    image: postgres
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rssapp
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    command: postgres -c 'max_connections=1000'

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

